### ISSUE TITLE
About the 1000 Genomes dataset

### ISSUE THREAD

**Issue by Caiyong-Yin** [23andMe/yhaplo#18]
Dear authors,

When I hanle the 1000 Genomes dataset by the code 'yhaplo -i 1000y.all.vcf.gz', the linux system responds that ‘ERROR. Could not open: 1000Y.all.vcf.gz’. I have check the path and the name of the data. So how could I solve this problem?

Caiyong Yin
Fudan University

**Comment by dpoznik** [comment]
Hmm, I just downloaded a fresh copy of the file from:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/chrY/ALL.chrY_10Mbp_mask.glia_freebayes_maxLikGT_siteQC.20130502.60555_biallelic_snps.vcf.gz

I then ran:
```
ln -sf ALL.chrY_10Mbp_mask.glia_freebayes_maxLikGT_siteQC.20130502.60555_biallelic_snps.vcf.gz 1000y.all.vcf.gz
yhaplo -i 1000y.all.vcf.gz
```

And it worked fine. So I'm guessing your download was corrupted. You could try reading the file with `tabix`:
```
tabix -p vcf 1000y.all.vcf.gz
tabix -H 1000y.all.vcf.gz
```
But it's probably easiest to just re-download.

**Comment by Caiyong-Yin** [comment]
Thanks. My issue has been solved following your suggestions.




            
            
                
                    
                            
                                
                            
                            
                                cyyin18
                            
                            
                                
                            
                    
                        
                            
                                    邮箱：cyyin18@fudan.edu.cn
                            
                        
                
            
        


On 10/22/2020 01:58, David Poznik wrote: 
Hmm, I just downloaded a fresh copy of the file from:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/chrY/ALL.chrY_10Mbp_mask.glia_freebayes_maxLikGT_siteQC.20130502.60555_biallelic_snps.vcf.gz
I then ran:
ln -sf ALL.chrY_10Mbp_mask.glia_freebayes_maxLikGT_siteQC.20130502.60555_biallelic_snps.vcf.gz 1000y.all.vcf.gz
yhaplo -i 1000y.all.vcf.gz

And it worked fine. So I'm guessing your download was corrupted. You could try reading the file with tabix:
tabix -p vcf 1000y.all.vcf.gz
tabix -H 1000y.all.vcf.gz

But it's probably easiest to just re-download.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/23andMe/yhaplo/issues/18#issuecomment-713754332",
"url": "https://github.com/23andMe/yhaplo/issues/18#issuecomment-713754332",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
