### ISSUE TITLE
BT-M42 calls in some samples

### ISSUE THREAD

**Issue by jaurbanChicago** [23andMe/yhaplo#37]
Hi, 

I am observing that Yhaplo is saying that I have some samples with BT-M42. If I understand correctly, this is a pretty big haplogroup, so is there any reason why it's telling me than? Is the program failing to narrow it down?

Thanks in advance!!

**Comment by dpoznik** [comment]
Yes, BT is about as broad as it gets (see page 5 of the [manuscript](https://www.biorxiv.org/content/10.1101/088716v1)) and unlikely to be the right call. If you run with the `--all_aux_output` option, Yhaplo will generate a bunch of supplementary files indicating that paths it took and which alleles it observed in the ancestral and derived states along those paths. These files should shed some light. See the manual for details on how to interpret them.

A couple things worth checking:
- Yhaplo assumes physical positions are in GRCh37 coordinates
- With extremely low-coverage sequencing, Yhaplo may not have enough data to work with
- Older men may experience chimeric Y-chromosome loss. As such, you may not have sufficient Y-chromosome DNA for some individuals in your sample. It's definitely worth checking call-rate, etc.

I hope that helps.
